// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Septembar2024Grupa1;

#nullable disable

namespace Septembar2024Grupa1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Septembar2024Grupa1.Models.Racun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CenaKomunalija")
                        .HasColumnType("int");

                    b.Property<int>("CenaStruje")
                        .HasColumnType("int");

                    b.Property<int>("CenaVode")
                        .HasColumnType("int");

                    b.Property<int>("MesecIzdavanja")
                        .HasColumnType("int");

                    b.Property<bool>("Placen")
                        .HasColumnType("bit");

                    b.Property<int>("StanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StanId");

                    b.ToTable("Racuni");
                });

            modelBuilder.Entity("Septembar2024Grupa1.Models.Stan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojClanova")
                        .HasColumnType("int");

                    b.Property<string>("ImeVlasnika")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Povrsina")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stanovi");
                });

            modelBuilder.Entity("Septembar2024Grupa1.Models.Racun", b =>
                {
                    b.HasOne("Septembar2024Grupa1.Models.Stan", "Stan")
                        .WithMany("Racuni")
                        .HasForeignKey("StanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stan");
                });

            modelBuilder.Entity("Septembar2024Grupa1.Models.Stan", b =>
                {
                    b.Navigation("Racuni");
                });
#pragma warning restore 612, 618
        }
    }
}
