// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oktobar2025Grupa2;

#nullable disable

namespace Oktobar2025Grupa2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251017151933_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Oktobar2025Grupa2.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojOcena")
                        .HasColumnType("int");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ProducentskaKucaId")
                        .HasColumnType("int");

                    b.Property<double>("ProsecnaOcena")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProducentskaKucaId");

                    b.ToTable("Filmovi");
                });

            modelBuilder.Entity("Oktobar2025Grupa2.Models.ProducentskaKuca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("ProducentskeKuce");
                });

            modelBuilder.Entity("Oktobar2025Grupa2.Models.Film", b =>
                {
                    b.HasOne("Oktobar2025Grupa2.Models.ProducentskaKuca", "ProducentskaKuca")
                        .WithMany("Filmovi")
                        .HasForeignKey("ProducentskaKucaId");

                    b.Navigation("ProducentskaKuca");
                });

            modelBuilder.Entity("Oktobar2025Grupa2.Models.ProducentskaKuca", b =>
                {
                    b.Navigation("Filmovi");
                });
#pragma warning restore 612, 618
        }
    }
}
