// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oktobar2025Grupa1;

#nullable disable

namespace Oktobar2025Grupa1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251018174240_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HamburgerSastojak", b =>
                {
                    b.Property<int>("HamburgeriId")
                        .HasColumnType("int");

                    b.Property<int>("SastojciId")
                        .HasColumnType("int");

                    b.HasKey("HamburgeriId", "SastojciId");

                    b.HasIndex("SastojciId");

                    b.ToTable("HamburgerSastojak");
                });

            modelBuilder.Entity("Oktobar2025Grupa1.Models.Hamburger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Prodat")
                        .HasColumnType("bit");

                    b.Property<int?>("ProdavnicaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdavnicaId");

                    b.ToTable("Hamburgeri");
                });

            modelBuilder.Entity("Oktobar2025Grupa1.Models.Prodavnica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Prodavnice");
                });

            modelBuilder.Entity("Oktobar2025Grupa1.Models.Sastojak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Debljina")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Sastojci");
                });

            modelBuilder.Entity("HamburgerSastojak", b =>
                {
                    b.HasOne("Oktobar2025Grupa1.Models.Hamburger", null)
                        .WithMany()
                        .HasForeignKey("HamburgeriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oktobar2025Grupa1.Models.Sastojak", null)
                        .WithMany()
                        .HasForeignKey("SastojciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Oktobar2025Grupa1.Models.Hamburger", b =>
                {
                    b.HasOne("Oktobar2025Grupa1.Models.Prodavnica", "Prodavnica")
                        .WithMany("Hamburgeri")
                        .HasForeignKey("ProdavnicaId");

                    b.Navigation("Prodavnica");
                });

            modelBuilder.Entity("Oktobar2025Grupa1.Models.Prodavnica", b =>
                {
                    b.Navigation("Hamburgeri");
                });
#pragma warning restore 612, 618
        }
    }
}
