// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Septembar2024Grupa2;

#nullable disable

namespace Septembar2024Grupa2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Septembar2024Grupa2.Models.Kupovina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UkupnaCena")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Kupovine");
                });

            modelBuilder.Entity("Septembar2024Grupa2.Models.Proizvod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<string>("DuziOpis")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<string>("KratakOpis")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Proizvodi");
                });

            modelBuilder.Entity("Septembar2024Grupa2.Models.ProizvodKupovina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KupovinaId")
                        .HasColumnType("int");

                    b.Property<int>("ProizvodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KupovinaId");

                    b.HasIndex("ProizvodId");

                    b.ToTable("ProizvodiKupovine");
                });

            modelBuilder.Entity("Septembar2024Grupa2.Models.ProizvodKupovina", b =>
                {
                    b.HasOne("Septembar2024Grupa2.Models.Kupovina", "Kupovina")
                        .WithMany("Proizvodi")
                        .HasForeignKey("KupovinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Septembar2024Grupa2.Models.Proizvod", "Proizvod")
                        .WithMany("Kupovine")
                        .HasForeignKey("ProizvodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kupovina");

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("Septembar2024Grupa2.Models.Kupovina", b =>
                {
                    b.Navigation("Proizvodi");
                });

            modelBuilder.Entity("Septembar2024Grupa2.Models.Proizvod", b =>
                {
                    b.Navigation("Kupovine");
                });
#pragma warning restore 612, 618
        }
    }
}
